//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "data_key")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub resource_uri: String,
    pub encrypted_data_key: String,
    pub iv: String,
    pub tag: String,
    pub aad: String,
    pub gmt_create: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
